name: Update BPMN Visualization version
on:
  repository_dispatch:
    types: [update_bpmn_visualization_version]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      build_demo_repo:
        description: 'The repository where the demo artifact is stored'
        default: "process-analytics/bpmn-visualization-js"
      build_demo_workflow_id:
        description: 'The workflow identifier or file name where the demo artifact is stored'
        default: "upload-demo-archive-and-trigger-examples-repository-update.yml"

        // To change. no bpmn-visualization.min.js in demo atifact
      artifact_name:
        description: 'The demo artifact name'
        default: "demo_"
        required: true

jobs:
  updateVersion:
    runs-on: ubuntu-20.04
    env:
      VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}
      ARTIFACT_NAME: ${{ github.event.client_payload.artifact_name || github.event.inputs.artifact_name }}
      BUILD_DEMO_WORKFLOW_ID: ${{ github.event.client_payload.build_demo_workflow_id || github.event.inputs.build_demo_workflow_id }}
      BUILD_DEMO_REPO: ${{ github.event.client_payload.build_demo_repo || github.event.inputs.build_demo_repo }}
    steps:
      - uses: actions/checkout@v2
      - name: Delete old BPMN Visualization version
        run: rm -rf inst/htmlwidgets/lib/bpmn-visualization

        // To change. no bpmn-visualization.min.js in demo atifact
      - name: Download BPMN Visualization ${{ env.VERSION }}
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ env.BUILD_DEMO_REPO }}
          workflow: ${{ env.BUILD_DEMO_WORKFLOW_ID }}
          workflow_conclusion: success
          name: ${{ env.ARTIFACT_NAME }}
          path: inst/htmlwidgets/lib/bpmn-visualization


      - name: Update BPMN Visualization version in YAML file
        run: sed -i -E "s/version: \".*\"/version: \"${{ env.VERSION }}\"/" inst/htmlwidgets/bpmnVisualization.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          commit-message: "[INFRA] Update BPMN Visualization version to ${{ env.VERSION }}"
          committer: "process-analytics-bot <62586190+process-analytics-bot@users.noreply.github.com>"
          author: "process-analytics-bot <62586190+process-analytics-bot@users.noreply.github.com>"
          branch: "infra/update_bpmn_visualization_to_${{ env.VERSION }}"
          delete-branch: true
          base: "master"
          title: "[INFRA] Update BPMN Visualization version to ${{ env.VERSION }}"
          body: ""
          labels: "enhancement"
          team-reviewers: js-lib-collaborators
          draft: true
